version: "3.8"
services:
  db1:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api1_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  db2:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api2_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  api1:
    build:
      context: ./api1
      dockerfile: Dockerfile.api1
    depends_on:
      - db1
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db1:5432/api1_db

  frontend:
    build:
      context: ./frontend/crud-dashboard
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - api1

  api2:
    build:
      context: ./api2
      dockerfile: Dockerfile.api2
    depends_on:
      - db2
      - api1
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db2:5432/api2_db
      - API1_URL=http://localhost:8001/products

volumes:
  postgres_data1:
  postgres_data2: